// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RefreshListController from "./refresh_list_controller"
application.register("refresh-list", RefreshListController)

import ShowMoreController from "./show_more_controller"
application.register("show-more", ShowMoreController)
